import type { Template, Font } from '@pdfme/common';
import {
  text,
  multiVariableText,
  image,
  svg,
  table,
  barcodes,
  line,
  rectangle,
  ellipse,
  dateTime,
  date,
  time,
  select,
  radioGroup,
  checkbox,
} from '@pdfme/schemas';

export const getPdfmeFonts = (): Font => ({
  Sarabun: {
    data: `${window.location.origin}/fonts/Sarabun-Regular.ttf`,
    fallback: true,
  },
  'Sarabun-Bold': {
    data: `${window.location.origin}/fonts/Sarabun-Bold.ttf`,
  },
});

export const getPdfmePlugins = () => ({
  // Text
  Text: text,
  MultiVariableText: multiVariableText,
  // Graphics
  Image: image,
  Svg: svg,
  // Shapes
  Line: line,
  Rectangle: rectangle,
  Ellipse: ellipse,
  // Table
  Table: table,
  // Date & Time
  DateTime: dateTime,
  Date: date,
  Time: time,
  // Form Controls
  Select: select,
  RadioGroup: radioGroup,
  Checkbox: checkbox,
  // Barcodes (QR, EAN13, Code128, etc.)
  ...barcodes,
});

export const getBlankTemplate = (): Template => ({
  basePdf: { width: 210, height: 297, padding: [15, 15, 15, 15] } as any,
  schemas: [[]],
});

export const getAdvancePaymentStarterTemplate = (): Template => ({
  basePdf: { width: 210, height: 297, padding: [10, 10, 10, 10] } as any,
  schemas: [[
    {
      name: 'formTitle',
      type: 'text',
      position: { x: 55, y: 12 },
      width: 100,
      height: 10,
      fontSize: 18,
      fontName: 'Sarabun-Bold',
      alignment: 'center',
      content: 'ใบขออนุมัติ',
    },
    {
      name: 'formSubtitle',
      type: 'text',
      position: { x: 55, y: 22 },
      width: 100,
      height: 8,
      fontSize: 14,
      fontName: 'Sarabun',
      alignment: 'center',
      content: 'เบิกเงินล่วงหน้า',
    },
    {
      name: 'formDate',
      type: 'text',
      position: { x: 55, y: 30 },
      width: 100,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun',
      alignment: 'center',
    },
    {
      name: 'runNumber',
      type: 'text',
      position: { x: 150, y: 12 },
      width: 50,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun-Bold',
      alignment: 'right',
    },
    {
      name: 'sectionEmployee',
      type: 'text',
      position: { x: 10, y: 48 },
      width: 60,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun-Bold',
      fontColor: '#0066cc',
      content: 'ข้อมูลผู้ขอเบิก',
    },
    {
      name: 'employeeName',
      type: 'text',
      position: { x: 10, y: 58 },
      width: 90,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun',
    },
    {
      name: 'employeePosition',
      type: 'text',
      position: { x: 110, y: 58 },
      width: 90,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun',
    },
    {
      name: 'employeeDepartment',
      type: 'text',
      position: { x: 10, y: 68 },
      width: 90,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun',
    },
    {
      name: 'requestAmount',
      type: 'text',
      position: { x: 110, y: 68 },
      width: 90,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun-Bold',
      fontColor: '#0066cc',
    },
    {
      name: 'activityType',
      type: 'text',
      position: { x: 10, y: 82 },
      width: 190,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun',
    },
    {
      name: 'activityDates',
      type: 'text',
      position: { x: 10, y: 92 },
      width: 190,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun',
    },
    {
      name: 'sectionExpense',
      type: 'text',
      position: { x: 10, y: 106 },
      width: 60,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun-Bold',
      content: 'รายละเอียดค่าใช้จ่าย',
    },
    {
      name: 'expenseDetails',
      type: 'text',
      position: { x: 10, y: 116 },
      width: 190,
      height: 60,
      fontSize: 11,
      fontName: 'Sarabun',
    },
    {
      name: 'totalAmount',
      type: 'text',
      position: { x: 110, y: 180 },
      width: 90,
      height: 10,
      fontSize: 14,
      fontName: 'Sarabun-Bold',
      fontColor: '#0066cc',
      alignment: 'right',
    },
    {
      name: 'details',
      type: 'text',
      position: { x: 10, y: 198 },
      width: 190,
      height: 20,
      fontSize: 11,
      fontName: 'Sarabun',
    },
    {
      name: 'sectionBank',
      type: 'text',
      position: { x: 10, y: 222 },
      width: 80,
      height: 7,
      fontSize: 12,
      fontName: 'Sarabun-Bold',
      fontColor: '#0066cc',
      content: 'ข้อมูลบัญชีธนาคาร',
    },
    {
      name: 'bankInfo',
      type: 'text',
      position: { x: 10, y: 232 },
      width: 190,
      height: 18,
      fontSize: 11,
      fontName: 'Sarabun',
    },
    {
      name: 'userSignatureLabel',
      type: 'text',
      position: { x: 10, y: 260 },
      width: 60,
      height: 7,
      fontSize: 10,
      fontName: 'Sarabun',
      alignment: 'center',
      content: 'ผู้ขอเบิก',
    },
    {
      name: 'userSignature',
      type: 'image',
      position: { x: 15, y: 268 },
      width: 40,
      height: 18,
    },
    {
      name: 'managerSignatureLabel',
      type: 'text',
      position: { x: 140, y: 260 },
      width: 60,
      height: 7,
      fontSize: 10,
      fontName: 'Sarabun',
      alignment: 'center',
      content: 'ผู้อนุมัติ',
    },
    {
      name: 'managerSignature',
      type: 'image',
      position: { x: 145, y: 268 },
      width: 40,
      height: 18,
    },
  ] as any],
});

export const getAdvancePaymentSampleInput = (): Record<string, string>[] => [{
  formDate: 'วันที่ 09 กุมภาพันธ์ 2569',
  runNumber: 'เลขที่: GADV202602001',
  employeeName: 'ชื่อ-นามสกุล: สมชาย ใจดี',
  employeePosition: 'ตำแหน่ง: พนักงานขาย',
  employeeDepartment: 'แผนก: Strategy',
  requestAmount: 'จำนวนเงิน: 12,000.00 บาท',
  activityType: 'ประเภท: จัดประชุม',
  activityDates: 'วันที่ 15 ก.พ. 2569 - 17 ก.พ. 2569  จำนวนผู้เข้าร่วม 80 คน',
  expenseDetails: '1. ค่าอาหาร และ เครื่องดื่ม    8,000.00 บาท\n2. ค่าที่พัก    4,000.00 บาท',
  totalAmount: 'รวมทั้งสิ้น: 12,000.00 บาท',
  details: 'รายละเอียด: เบิกเงินทดรองสำหรับจัดประชุมทีมขาย',
  bankInfo: 'ชื่อบัญชี: สมชาย ใจดี\nธนาคาร: ธนาคารกรุงเทพ (Bangkok Bank)\nเลขที่บัญชี: 1234567890',
}];
