-- Add generated_html_content column to announcements table
ALTER TABLE announcements 
ADD COLUMN IF NOT EXISTS generated_html_content TEXT;

-- Add comment
COMMENT ON COLUMN announcements.generated_html_content IS 'HTML content generated by AI for rich announcement display';
