// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpqetfmwiydzsaltvyxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcWV0Zm13aXlkenNhbHR2eXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDA2MjksImV4cCI6MjA2MzQ3NjYyOX0.5fb9S3nbrXMdWYlgUSgsve_ym4cDNd2MaZRB_2GnBts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);